config/routes.rb
Rails.application.routes.draw do
   devise_for :users
    root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  get "search" => "searches#search"

 resources :books, only: [:new, :index, :show, :create, :edit, :update,:destroy] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end

 resources :users, only: [:index, :show, :edit, :update] do
  get "search" => "users#search"
  resource :relationships, only: [:create, :destroy]
 	get "followings" => "relationships#followings", as: "followings"
  get "followers" => "relationships#followers", as: "followers"
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to  request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: options[:class].presence || "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: options[:class].presence || "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<table class='table table-hover table-inverse'>

  <% if @users.exists? %>
  <% @users.each do |user| %>
      <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
       <tr>
          <td><%= image_tag user.get_profile_image(80,80) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
      <% end %>
      </tbody>
      </table>
      <% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<table class='table table-hover table-inverse'>

  <% if @users.exists? %>
  <% @users.each do |user| %>
      <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
       <tr>
          <td><%= image_tag user.get_profile_image(80,80) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
      <% end %>
      </tbody>
      </table>
      <% else %>
  <p>ユーザーはいません</p>
<% end %>