config/routes.rb
Rails.application.routes.draw do
   devise_for :users
    root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  get "search" => "searches#search"

 resources :books, only: [:new, :index, :show, :create, :edit, :update,:destroy] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end

 resources :users, only: [:index, :show, :edit, :update] do
  get "search" => "users#search"
  resource :relationships, only: [:create, :destroy]
 	get "followings" => "relationships#followings", as: "followings"
  get "followers" => "relationships#followers", as: "followers"
  end

end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  #今日1日で作成した 全Bookを取得します。
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
   scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
   scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
   scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
   scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
   scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }
  #1~6日前で作成した 全Bookを取得します。
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  #6日前の0:00から今日の23:59までに作成した 全Bookを取得します。
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  #2週間前の0:00から1週間前の23:59までに作成した 全Bookを取得します。

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
   @book1 = Book.new
  end

  def create
    @user = current_user
    @book1 = Book.new(book_params)
    @book1.user_id = current_user.id
   if @book1.save
      flash[:notice] = "You have creatad book successfully."
   redirect_to book_path(@book1.id)
   else
    @books = Book.all
    flash[:notice] = ' errors prohibited this obj from being saved:'
    render :index
   end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book1 = Book.new
  end

  def show
    @user = current_user
    @book = Book.find(params[:id])
    @book1 = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render :edit
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
     @book.destroy
      redirect_to books_path
  end

   private

  def book_params
      params.require(:book).permit(:title, :body)
  end

 def is_matching_login_user
    book = Book.find(params[:id])
    user = book.user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
      <div class="col-md-3">
        <h2>User info</h2>
      <%= image_tag user.get_profile_image(100,100) %>
        <table class="table">
          <tbody>
            <tr>
            </tr>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
            <tr>
            <th>follows</th>
            <th><%= link_to user.followings.count, user_followings_path(user) %></th>
            </tr>
            <tr>
            <th>followers</th>
            <th><%= link_to user.followers.count, user_followers_path(user) %></th>
            </tr>
          </tbody>
        </table>
       <div class="row">
        <% if current_user != user %>
        <td><%= render "relationships/btn", user: user, options: { class: ""} %></td>
        <% else %>
        <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
       <% end %>
       </div>
        <h2 class="mt-3">
          New book
        </h2>
        <%= form_with model: @book1 do |f| %>
          <div class="form-group">
            <label>Title</label>
            <%= f.text_field :title ,class: "form-control book_title"%>
          </div>
          <div class="form-group">
            <label>Opinion</label>
            <%= f.text_area :body ,class: "form-control book_body"%>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: "btn btn-success"%>
          </div>


        <% end %>
      </div>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <div id="error_explanation">
        <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
          <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="Title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="Opinion">Opinion</label>
          <%= f.text_area :body,class: "form-control book_body"%>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book" ,class: "btn btn-success"%>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div id="error_explanation">
        <% if @book1.errors.any? %>
        <h3><%= @book1.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book1.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="row">
      <%= render 'books/book', user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
       <thead>
       <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
       </tr>
       </thead>
          <tbody>
 <% @books.each do |book| %>
  <tr>
    <td>
    <%= link_to user_path(book.user_id) do %>
     <%= image_tag book.user.get_profile_image(80,80) %>
    <% end %>
     </td>
     <td>
     <%= link_to book_path(book.id) do %>
     <%= book.title %>
     <% end %>
     </td>
    <td>
    <%= book.body %>
    </td>
       <td id="favorite_btn_<%= book.id %>">
         <%= render "favorites/favorite-btn", book: book %>
       </td>
  <td class="comments-count">コメント数: <%= book.book_comments.count %></td>
   </tr>
  <% end %>
  </tbody>
</table>
  </div>
  </div>
  </div>
</main>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @post_image do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<main>
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'books/book', user: @book.user %>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
            <tr>
             <td>
               <%= link_to user_path(@book.user_id) do %>
               <%= image_tag @book.user.get_profile_image(100,100) %>
               <br>
               <%= @book.user.name %>
               <% end %>
             </td>

             <td>
              <%= link_to book_path(@book.id) do %>
              <%= @book.title %>
              <% end %>
             </td>
              <td><%= @book.body %></td>
           <td id="favorite_btn_<%= @book.id %>">
             <%= render "favorites/favorite-btn", book: @book %>
           </td>
             <td id="comment_counter">
                <%= render "book_comments/counter", book: @book %>
             </td>
              <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book.id) , class: "btn btn-sm btn-success"%></td>
                <td><%= link_to "Destroy", book_path(@book.id) , method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger"%></td>
              <% end %>
            </tr>
        </tbody>
       </table>
        <table class="table">
          <tbody id="comment_index">
          <%= render 'book_comments/index', book: @book %>
          </tbody>
        </table>
     <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
  
</main>