config/routes.rb
Rails.application.routes.draw do
   devise_for :users
    root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  get "search" => "searches#search"

 resources :books, only: [:new, :index, :show, :create, :edit, :update,:destroy] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end

 resources :users, only: [:index, :show, :edit, :update] do
  get "search" => "users#search"
  resource :relationships, only: [:create, :destroy]
 	get "followings" => "relationships#followings", as: "followings"
  get "followers" => "relationships#followers", as: "followers"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <script src="https://kit.fontawesome.com/46b63c17d2.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
   <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse show" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "/books", class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i>Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>Log out
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "/", class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= flash[:notice] %>
    <div class="d-flex justify-content-center mb-2">
       <%= render "searches/search" %>
    </div>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>